//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceExecutorModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckPost
    {
        public int Id { get; set; }
        public string BIBCode { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    }
}
