//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceExecutorModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Race
    {
        public long Id { get; set; }
        public string RaceName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Location { get; set; }
        public string Sponsers { get; set; }
        public string Comment { get; set; }
    }
}
