//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceExecutorModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int Id { get; set; }
        public Nullable<long> BIBCode { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<long> RaceId { get; set; }
        public string Nationality { get; set; }
        public string SeasonPass { get; set; }
        public string TeamName { get; set; }
        public string AgeOnRaceDay { get; set; }
        public string Gender_Image { get; set; }
        public string CategoryImage { get; set; }
    }
}
