//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceExecutorModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TrailRaceNepalEntities : DbContext
    {
        public TrailRaceNepalEntities()
            : base("name=TrailRaceNepalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CheckPost> CheckPosts { get; set; }
        public virtual DbSet<CheckStation> CheckStations { get; set; }
        public virtual DbSet<Race> Races { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<TimeInterval> TimeIntervals { get; set; }
        public virtual DbSet<View17andBelowFemaleRankedList> View17andBelowFemaleRankedList { get; set; }
        public virtual DbSet<View17andBelowMaleRankedList> View17andBelowMaleRankedList { get; set; }
        public virtual DbSet<View18to39FemaleRankedList> View18to39FemaleRankedList { get; set; }
        public virtual DbSet<View18to39MaleRankedList> View18to39MaleRankedList { get; set; }
        public virtual DbSet<View40andAboveFemaleRankedList> View40andAboveFemaleRankedList { get; set; }
        public virtual DbSet<View40andAboveMaleRankedList> View40andAboveMaleRankedList { get; set; }
        public virtual DbSet<View8andBelowFemaleRankedList> View8andBelowFemaleRankedList { get; set; }
        public virtual DbSet<View8andBelowMaleRankedList> View8andBelowMaleRankedList { get; set; }
        public virtual DbSet<ViewOverAllFemaleRankedList> ViewOverAllFemaleRankedLists { get; set; }
        public virtual DbSet<ViewOverAllMaleRankedList> ViewOverAllMaleRankedLists { get; set; }
        public virtual DbSet<View11andBelowFemaleRankedList> View11andBelowFemaleRankedList { get; set; }
        public virtual DbSet<View11andBelowMaleRankedList> View11andBelowMaleRankedList { get; set; }
        public virtual DbSet<View12to17FemaleRankedList> View12to17FemaleRankedList { get; set; }
        public virtual DbSet<View12to17MaleRankedList> View12to17MaleRankedList { get; set; }
    
        public virtual ObjectResult<string> SpMissedRunnersCheckinSel(Nullable<long> raceId)
        {
            var raceIdParameter = raceId.HasValue ?
                new ObjectParameter("RaceId", raceId) :
                new ObjectParameter("RaceId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SpMissedRunnersCheckinSel", raceIdParameter);
        }
    
        public virtual int SpTimeIntervalIns(Nullable<long> raceId, Nullable<System.DateTime> startTime, Nullable<System.DateTime> endTime, Nullable<System.TimeSpan> interval, Nullable<long> bIBCode, ObjectParameter returnMessage)
        {
            var raceIdParameter = raceId.HasValue ?
                new ObjectParameter("RaceId", raceId) :
                new ObjectParameter("RaceId", typeof(long));
    
            var startTimeParameter = startTime.HasValue ?
                new ObjectParameter("StartTime", startTime) :
                new ObjectParameter("StartTime", typeof(System.DateTime));
    
            var endTimeParameter = endTime.HasValue ?
                new ObjectParameter("EndTime", endTime) :
                new ObjectParameter("EndTime", typeof(System.DateTime));
    
            var intervalParameter = interval.HasValue ?
                new ObjectParameter("Interval", interval) :
                new ObjectParameter("Interval", typeof(System.TimeSpan));
    
            var bIBCodeParameter = bIBCode.HasValue ?
                new ObjectParameter("BIBCode", bIBCode) :
                new ObjectParameter("BIBCode", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SpTimeIntervalIns", raceIdParameter, startTimeParameter, endTimeParameter, intervalParameter, bIBCodeParameter, returnMessage);
        }
    }
}
