//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceExecutorModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class View17andBelowFemaleRankedList
    {
        public int Id { get; set; }
        public Nullable<long> BIBCode { get; set; }
        public string Name { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<System.TimeSpan> Interval { get; set; }
        public Nullable<long> RANK { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<long> RaceId { get; set; }
    }
}
